# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: wolfs_schanze
email: wolfs_schanze@outlook.de
description: >- # this means to ignore newlines until "baseurl:"
  wolfs schanze ist ein podcast der seinen beitrag zur kulturmaximierung leistet.
baseurl: "/wolfs_schanze"
url: "https://schanzendasein.github.io/"
twitter_username: schanzendasein
github_username:  schanzendasein
header_pages:
  - index.md
  - about.md
  - contact.md
# Build settings
# theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-patreon

style: dark
# Build settings
markdown: kramdown
footer: '<a href="https://feeds.soundcloud.com/users/soundcloud:users:778690900/sounds.rss">rss</a>'

remote_theme: b2a3e8/jekyll-theme-console

####################
# Patreon Settings #
####################

patreon:
    enabled: true
    design: 'default' # Supports the following desings: default, fancy, minimal, streamlined, reversed, swapped
    title: 'Example title'
    metercolor: 'green nostripes' # Supports the following colors: red, green, orange, red nostripes, green nostripes, orange nostripes, blue nostripes
    toptext: 'Example top text' # Text that appears in before the progress bar (optional)
    bottomtext: 'Example bottom text' # Text that appears in after the progress bar (optional)
    showgoaltext: true # Display the goal text?
    showbutton: true # Display the "Become a patron" button?
    username: 'wolfs_schanze'
    default_lang: "en" # The default language to use (to avoid writing twice the same text from Patreon)


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
